# Site settings
title: Tmyyâ€™s Blog
SEOTitle: å¤©å‘½å¹½äº‘çš„ä¸ªäººåšå®¢ | Tmyyâ€™s Blog
header-img: /icon.png
email: mzxtiamy@gmail.com	
description: "å¤©å‘½å¹½äº‘çš„ä¸ªäººåšå®¢"
keyword: "å¤©å‘½å¹½äº‘, tmyy, Tmyy, TMYY, XC1oud, XenonCloud, Blog, åšå®¢"
url: "https://xenoncloudtmyy.github.io"
baseurl: ""

# Sidebar settings
sidebar: true
sidebar-about-description: "å…¨ä¸–ç•Œæœ€ç‰›é€¼çš„äººğŸ˜"
sidebar-avatar:/icon.png
